# pull official base image
FROM python:3.8.3-alpine

WORKDIR /app
ADD ./backend/requirements.txt /app/backend/

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install --upgrade pip
RUN pip install gunicorn
RUN pip3 install djangorestframework 
RUN pip install -r /app/backend/requirements.txt

ADD ./docker /app/docker
ADD ./backend /app/backend