version: '3.7'

services:
    nginx: 
        container_name: nginx_dev
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile.dev
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/server/django_static
            - ./docker/nginx/development:/etc/nginx/conf.d
        depends_on: 
            - backend
    backend:
        container_name: backend_dev
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile            
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/server/django_static
        expose:
            - 8000     
    frontend:
        container_name: frontend_dev
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile   
        volumes:
            - '.:/app/frontend/'
            - '/app/frontend/node_modules'
        expose:
            - 3000

volumes:
    static_volume: {}
