version: '3.7'

services:
    nginx: 
        container_name: nginx_prod
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile.prod
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_volume:/app/backend/base/django_static
            - ./docker/nginx/production:/etc/nginx/conf
        depends_on: 
            - backend       
    backend:
        container_name: backend_prod
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/base/django_static
        expose:
            - 8000        

volumes:
    static_volume: {}
