version: '3.7'

services:
    backend:
        container_name: backend_dev
        build:
            context: ./backend
            dockerfile: Dockerfile.dev   
        volumes:
            - ./app/:/usr/src/app/
        env_file:
            - ./.env.dev
        ports:
            - 8000:8000
        depends_on: 
            - db
    frontend:
        container_name: frontend_dev
        build:
            context: ./frontend
            dockerfile: Dockerfile   
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    db:
        container_name: postgresql_dev
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev

volumes:
    postgres_data:
