version: '3.7'

services:
    backend:
        container_name: backend_dev
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile.dev   
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/server/django_static
        env_file:
            - ./.env.dev
        ports:
            - 8000:8000
        depends_on: 
            - postgresql
    frontend:
        container_name: frontend_dev
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile   
        volumes:
            - '/app/frontend/'
            - '/app/frontend/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    postgresql:
        container_name: postgresql_dev
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev

volumes:
    static_volume: {}
    postgres_data:
