version: '3.7'

services:
    backend:
        container_name: backend_dev
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile.dev         
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/server/django_static
        expose:
            - 8000     
    frontend:
        container_name: frontend_dev
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile   
        volumes:
            - '/app/frontend/'
            - '/app/frontend/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true

volumes:
    static_volume: {}
